# Generated by Django 3.1.12 on 2025-06-13 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('audio_file', models.FileField(upload_to='audio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg'])])),
                ('category', models.CharField(choices=[('GENGETONE', 'gengetone'), ('Hip Hop', 'rap'), ('AFRO', 'afro'), ('OTHER', 'other')], default='OTHER', max_length=20)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('tempo', models.CharField(max_length=20)),
                ('key', models.CharField(max_length=20)),
                ('duration', models.CharField(blank=True, max_length=20)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
